services:
  redis:
    image: redis
    container_name: redis_c1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    restart: always

  django-project:
    container_name: django_c1
    build:
      context: .
      dockerfile: Dockerfile
    image: django-image
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - venv:/app/venv
    depends_on:
      - redis
    command: >
      bash -c "
        cd /app/iitbhilai_mess &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    restart: always

volumes:
  redis_data:
  venv:
