# Generated by Django 6.0.6 on 2026-08-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('kind', models.CharField(choices=[('special', 'Special Dinner / Event'), ('timing', 'Changed Meal Timings'), ('meal', 'Changed Meal / Menu'), ('general', 'General')], default='general', max_length=20)),
                ('color', models.CharField(choices=[('#d4183d', 'Red'), ('#d97706', 'Amber'), ('#2541b2', 'Blue'), ('#10b981', 'Green'), ('#45347d', 'Purple')], default='#45347d', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('1&3 Week', 'Week 1 & 3'), ('2&4', 'Week 2 & 4')], default='1&3 Week', max_length=20)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('slot', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('Tea Time', 'Tea Time / Snacks'), ('DINNER', 'Dinner')], max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('item', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Menu',
                'ordering': ['week', 'day'],
            },
        ),
    ]
