# Generated by Django 6.0.6 on 2026-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('Rules', 'Rules'), ('Timings', 'Timings'), ('Hygiene', 'Hygiene'), ('Guests', 'Guests'), ('Feedback', 'Feedback'), ('Other', 'Other')], default='Other', max_length=20)),
                ('color', models.CharField(choices=[('#d4183d', 'Red'), ('#d97706', 'Amber'), ('#2541b2', 'Blue'), ('#10b981', 'Green'), ('#45347d', 'Purple'), ('#8e7db4', 'Lavender')], default='#45347d', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
