



bind 0.0.0.0


port 6379


user default off
  

user Lakshyasoni on >Laksh@567 ~* +@all +select


appendonly yes


save 900 1
save 300 10
save 60 10000


logfile ""


rename-command FLUSHALL ""

rename-command FLUSHDB ""


protected-mode no
